# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  pull_request: # This will publish a site preview on every pull request
    branches: ["main"]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  env:
    PR_PATH: pull/${{github.event.number}}
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
      
      - name: Install Gems
        run: bundle install
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Set PR Path
        if: github.event_name == 'pull_request'
        run: echo "PR_PATH=${{ github.event.number }}" >> $GITHUB_ENV
      
      - name: Build with Jekyll
        if: github.ref == 'refs/heads/main'
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Build PR preview website
        if: github.ref != 'refs/heads/main'
        run: bundle exec jekyll build --baseURL "/${{ env.PR_PATH }}"
        env:
          JEKYLL_ENV: staging

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "Starting deployment of preview ⏳..."
    
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
      
      - name: Deploy PR preview
        if: github.ref != 'refs/heads/main'
        uses: actions/deploy-pages@v2
        with:
          destination_dir: ${{ env.PR_PATH }} # TODO you need to set this if you're using a custom domain. Otherwise you can remove it.

  - name: Comment on PR
        if: github.ref != 'refs/heads/main'
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "A preview of the changes has been deployed and can be viewed here: https://${{ github.repository }}.github.io/${{ env.PR_PATH }}"