# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]  # Runs on PRs to the default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      # Xây dựng site với Jekyll
      - name: Build with Jekyll
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Nếu là PR, dùng baseurl dựa trên số PR
            bundle exec jekyll build --baseurl "/pr-${{ github.event.number }}/"
          else
            # Nếu là nhánh chính, dùng baseurl chuẩn
            bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          fi
        env:
          JEKYLL_ENV: production
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          destination_dir: |
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              pr-${{ github.event.number }}
            else
              .
      
      # Nếu là PR, thêm bình luận với link bản review
      - name: Comment on PR with preview URL
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          header: 'Deploy Preview'
          message: "Preview your changes: https://${{ github.repository }}.github.io/pr-${{ github.event.number }}/"
